export const services = [
  {
    id: "01",
    icon: "✦",
    title: "AI Integration & Agentic Systems",
    desc: "I connect your product to Claude, GPT-4o, and beyond — streaming chat, AI copilots, RAG pipelines, and agentic workflows that feel native, not bolted on.",
  },
  {
    id: "02",
    icon: "⬡",
    title: "Frontend Engineering",
    desc: "Production-grade interfaces in React, Next.js, and Angular — with enough backend knowledge to own API contracts, data models, and deployment without handing off.",
  },
  {
    id: "03",
    icon: "◻",
    title: "Mobile App Engineering",
    desc: "Cross-platform iOS and Android apps with consistent performance and clean UI using React Native, Flutter, and Ionic/Capacitor.",
  },
  {
    id: "04",
    icon: "↑",
    title: "System Modernization",
    desc: "Legacy codebase? I migrate monoliths to micro-frontends or modular backends, roll out design systems, and rebuild architectures your team will actually enjoy working in.",
  },
  {
    id: "05",
    icon: "◉",
    title: "IoT & Hardware-Connected Systems",
    desc: "Production-grade hardware communication via WebSerial, WebUSB, BLE, and WiFi — built and deployed at scale across 5,000+ IoT devices.",
  },
  {
    id: "06",
    icon: "⚡",
    title: "Performance & Architecture Audit",
    desc: "Faster loads, tighter APIs, smarter caching — I've cut load times by 50% and API integration effort by 30% in production. Clear written audit + action plan.",
  },
  {
    id: "07",
    icon: "◈",
    title: "UI/UX Engineering",
    desc: "Structured UX audits and accessible, intuitive interfaces — designed to work, not just look good.",
  },
  {
    id: "08",
    icon: "◎",
    title: "Technical Leadership & Consultation",
    desc: "Architecture decisions, coding standards, design systems, and mentorship — I raise the bar for the whole team, not just my own output.",
  },
];

export const skillCategories = [
  {
    icon: "✦",
    title: "AI Integration",
    items: ["Claude API", "OpenAI", "LangChain", "RAG", "Streaming UIs", "AI Agents", "Prompt Engineering"],
  },
  {
    icon: "⬡",
    title: "Frontend & Mobile",
    items: ["React", "Next.js", "Angular", "React Native", "Flutter", "Ionic", "Capacitor"],
  },
  {
    icon: "◈",
    title: "Languages & State",
    items: ["TypeScript", "JavaScript ES6+", "Dart", "NgRx", "GraphQL", "SQL"],
  },
  {
    icon: "◉",
    title: "UI & Design Systems",
    items: ["Tailwind CSS", "SASS", "Shadcn", "Material UI", "AntD", "Bootstrap", "Figma"],
  },
  {
    icon: "◫",
    title: "IoT & Hardware APIs",
    items: ["WebSerial", "WebUSB", "BLE", "WiFi Provisioning", "Device Management", "Real-time Dashboards"],
  },
  {
    icon: "⊞",
    title: "Architecture",
    items: ["Micro-frontends", "Single-SPA", "NX Monorepo", "Design Systems", "PWA", "Component Libraries"],
  },
  {
    icon: "⊙",
    title: "DevOps & Tools",
    items: ["Git", "Docker", "CI/CD", "Webpack", "Jest/Enzyme", "Cypress", "GCP", "AWS", "Vercel"],
  },
];

export const projects = [
  {
    id: "01",
    title: "KamsGuard — IoT Device Management Portal",
    company: "Kamsware LTD",
    period: "Nov 2023 — Present",
    type: "Enterprise · IoT",
    problem: "5,000+ IoT devices across 5+ enterprise sites with no unified provisioning — every device required manual configuration, causing major inefficiency in setup and diagnostics.",
    outcome: "Built a hardware communication layer using WebSerial, WebUSB, BLE, and WiFi APIs, automating device provisioning and diagnostics end-to-end. Led frontend architecture for 1,000+ users across a real-time monitoring portal.",
    metrics: ["5,000+ devices automated", "96% provisioning efficiency gain", "50% faster load times", "150+ features shipped"],
    stack: ["Angular", "WebSerial", "WebUSB", "BLE", "NX Monorepo", "CI/CD"],
  },
  {
    id: "02",
    title: "Kyosk — Micro-frontend Migration",
    company: "Kyosk Digital",
    period: "Jul 2022 — Nov 2023",
    type: "Enterprise · Migration",
    problem: "A legacy monolith frontend blocked multiple teams from shipping independently, creating delivery bottlenecks and making each release a cross-team coordination effort.",
    outcome: "Migrated to Single-SPA micro-frontend architecture, implemented a company-wide design system, migrated REST APIs to GraphQL, and configured PWA bundle compression — enabling teams to ship fully independently.",
    metrics: ["50% developer velocity increase", "45% faster API response", "3× trip delivery volume", "70% mobile data cost reduction"],
    stack: ["React", "Single-SPA", "GraphQL", "PWA", "Design System", "TypeScript"],
  },
  {
    id: "03",
    title: "NTSA — Intelligent Transport System",
    company: "Data Integrated",
    period: "Nov 2020 — Dec 2021",
    type: "Government · Transport",
    problem: "Kenya's national transport authority needed a system to track and manage 500,000+ commercial vehicles with no existing digital infrastructure — built from scratch against a hard government deadline.",
    outcome: "Built the React UI across 40+ screens integrated with four microservice APIs, delivering the NTSA Intelligent Transport MVP on time. Also led redesign of a travel booking platform through user research.",
    metrics: ["500K+ vehicles tracked", "40+ screens delivered", "4 microservice APIs integrated", "+50% booking conversions"],
    stack: ["React", "Figma", "Microservices", "UX Research", "TypeScript"],
  },
  {
    id: "04",
    title: "Lehigh Talent Academy",
    company: "Lehigh Talent Academy",
    period: "2025",
    type: "Education · Corporate",
    url: "https://lehightalentacademy.com",
    problem: "A US-based talent development organisation needed a professional web presence with reliable CI/CD deployment and DNS configuration from scratch.",
    outcome: "Led delivery of lehightalentacademy.com — built Bitbucket CI pipelines, FTP deployment, and full DNS configuration end-to-end.",
    metrics: ["Live site delivered", "Full CI/CD pipeline", "US client, remote lead"],
    stack: ["Angular", "Bitbucket CI", "FTP Deploy", "DNS"],
  },
  {
    id: "05",
    title: "Lehigh Talent Academy Foundation",
    company: "Lehigh Talent Academy",
    period: "2026",
    type: "Education · Foundation",
    url: "https://lehightalentacademyfoundation.org",
    problem: "The foundation arm of Lehigh Talent Academy needed its own dedicated site separate from the academy — same CI/CD infrastructure, distinct brand and content.",
    outcome: "Led delivery of lehightalentacademyfoundation.org as a standalone site, reusing and extending the CI/CD pipeline already in place.",
    metrics: ["Standalone site delivered", "Shared CI/CD infrastructure", "US client, remote lead"],
    stack: ["Angular", "Bitbucket CI", "FTP Deploy", "DNS"],
  },
  {
    id: "06",
    title: "Carwash POS — Full-Stack SaaS Platform",
    company: "Mikrosell Systems",
    period: "2024",
    type: "SaaS · POS",
    url: "https://carwash.mikrosell.com",
    problem: "Carwash businesses managing transactions, staff, and reporting entirely manually — no receipts, no revenue tracking, no visibility into daily operations.",
    outcome: "Built the entire platform solo — React frontend, Node.js/MongoDB backend, automated email receipts via Nodemailer, staff management, and transaction reporting with dashboard analytics.",
    metrics: ["Solo full-stack delivery", "Full POS + reporting", "Automated receipts", "Live in production"],
    stack: ["React", "Node.js", "MongoDB", "Mongoose", "Nodemailer"],
  },
  {
    id: "07",
    title: "Kenwide Institute — Online German School",
    company: "Kenwide Institute",
    period: "2024",
    type: "Education · Web",
    url: "https://www.kenwideinstitute.com",
    problem: "An online German language school needed a professional platform to attract students, present courses and instructors, and establish credibility in a competitive language-learning market.",
    outcome: "Led frontend development for the full site — clean, course-focused, and optimised for student acquisition with clear navigation and structured course presentation.",
    metrics: ["Lead frontend", "Live production site", "International client"],
    stack: ["Angular", "TypeScript"],
  },
  {
    id: "08",
    title: "Efasol Solutions — Farm Management Platform",
    company: "Efasol Solutions",
    period: "2026",
    type: "AgriTech · SaaS",
    url: "https://app.efasolsolutions.com",
    problem: "Kenyan farmers had no digital system for logging field incidents or accessing a marketplace — all operations were manual and disconnected across the value chain.",
    outcome: "Built the entire platform solo — farm incident management module and farmer marketplace — with Next.js, MikroORM data layer, and fully automated GitHub Actions CI/CD from day one.",
    metrics: ["Solo full-stack delivery", "Incident mgmt + marketplace", "Automated CI/CD", "Live in production"],
    stack: ["Next.js", "MikroORM", "GitHub Actions", "TypeScript"],
  },
  {
    id: "09",
    title: "HEM — Church Choir Website",
    company: "HEM Church",
    period: "2026",
    type: "Web · Community",
    url: "https://hem.mikrosell.com",
    problem: "A church choir needed a digital home for their music, events, and community — fast to build, polished to present, and easy to maintain going forward.",
    outcome: "Solo-developed and deployed using Next.js with AI-assisted development — demonstrating end-to-end delivery speed with modern tooling. From brief to live in days.",
    metrics: ["Solo delivery", "AI-assisted development", "Days from brief to live"],
    stack: ["Next.js", "TypeScript", "AI-assisted"],
  },
];

export const careerItems = [
  {
    period: "Nov 2023 — Present",
    company: "Kamsware LTD",
    role: "Senior Frontend Engineer",
    summary: "Built and scaled hardware-connected frontend systems for 5,000+ IoT devices with a 96% provisioning and diagnostics efficiency improvement.",
    bullets: [
      "Delivered 150+ features across 3 projects with 95% on-time success through cross-timezone coordination with offshore tech lead.",
      "Reduced app loading times by 50% and API integration effort by 30% by architecting reusable Angular OData query modules with intelligent caching.",
      "Built a scalable hardware-communication architecture using WebSerial, WebUSB, BLE, and WiFi APIs — automating provisioning and diagnostics for 5,000+ IoT devices with a 96% efficiency improvement.",
      "Led frontend architecture for an enterprise IoT management portal serving 1,000+ users across 5+ sites with real-time notifications and device monitoring.",
      "Mentored 3 junior developers — 2 earned promotions within 12 months. Team delivery speed up by 50%.",
    ],
    tags: ["Angular", "IoT", "WebSerial", "BLE", "NX", "CI/CD"],
  },
  {
    period: "Jul 2022 — Nov 2023",
    company: "Kyosk Digital",
    role: "Senior Frontend Engineer",
    summary: "Migrated a legacy monolith to micro-frontends with Single-SPA, improving scalability and developer velocity by 50%.",
    bullets: [
      "Implemented a company-wide design system that standardised web and mobile interfaces, increasing component reusability and boosting user satisfaction by 40%.",
      "Migrated REST APIs to GraphQL, cutting app response times by 45% and enabling 3× higher trip delivery volumes.",
      "Migrated a legacy monolith to micro-frontend architecture using Single-SPA, improving scalability and developer velocity by 50%.",
      "Configured PWA bundle compression and caching, reducing mobile data usage cost by 70%.",
    ],
    tags: ["React", "GraphQL", "Single-SPA", "PWA", "Design System"],
  },
  {
    period: "Jan — Jul 2022",
    company: "Innovex Solutions",
    role: "Frontend Engineer",
    summary: "Architected an enterprise spare parts sourcing platform that reduced accident resolution time by 78%.",
    bullets: [
      "Architected an enterprise spare parts sourcing system for 60+ insurers and garages using Angular 16, TypeScript, and NgRx — reducing accident resolution time by 78%.",
      "Built a library of 20+ reusable Angular modules achieving 30% code reuse and cutting feature development time by 50%.",
      "Implemented automated visual regression testing, reducing UI bugs in production by 70%.",
    ],
    tags: ["Angular 16", "NgRx", "TypeScript", "Visual Testing"],
  },
  {
    period: "Nov 2020 — Dec 2021",
    company: "Data Integrated",
    role: "Frontend Engineer",
    summary: "Built the React UI for the NTSA Intelligent Transport MVP, tracking 500,000+ commercial vehicles across 40+ screens.",
    bullets: [
      "Led redesign of a travel booking platform through user interviews and usability testing — increased bookings by 50% and cut booking time by 30%.",
      "Built the React UI for the NTSA Intelligent Transport MVP, tracking 500,000+ commercial vehicles across 40+ Figma screens integrated with four microservice APIs.",
      "Established coding standards for a 5-engineer team reducing code review time by 40% and cutting technical debt by 60%.",
    ],
    tags: ["React", "Figma", "UX Research", "Microservices"],
  },
];

export const updates = [
  "/assets/illustration-1.jpg",
  "/assets/2Illustration1.png",
  "/assets/people-1.png",
  "/assets/people-2.png",
  "/assets/people-3.png",
  "/assets/Illustration2.png",
];
